### ISSUE TITLE
Invalid column name after update

### ISSUE THREAD

**Issue by SteffenLG** [Epicweb-Optimizely/Epicweb.Optimizely.RedirectManager#1]
Hi, I've followed the instructions in the README in order to upgrade from an old version to this new one. It says to rename "the table" to 'SEO_redirect', so I've renamed a table named 'SOLITA_Redirect' as instructed. 
I think this instruction could be clearer, as it was not clear to me which table should be renamed. The README also says "the schema" should be the same. I think this could be clearer as well, perhaps specifying the expected schema would avoid some confusion. 

My end result is the following:
`SqlException: Invalid column name 'Host'.
Invalid column name 'Host'.`
and
`InvalidOperationException: The exception handler configured on ExceptionHandlerOptions produced a 404 status response. This InvalidOperationException containing the original exception was thrown since this is often due to a misconfigured ExceptionHandlingPath. If the exception handler is expected to return 404 status responses then set AllowStatusCode404Response to true.`

So based on the first message I'm assuming the schema is not the same? Not sure what the second one is about. 

I would appreciate some help with this, in the mean time I suppose I'll start perusing the source code of this repository. Thanks in advance.

**Comment by LucGosso** [comment]
Hello! This is how it should look

![image](https://user-images.githubusercontent.com/9716195/231706843-b4b5e9f2-d32f-41d4-9c79-09371f1b105d.png)

How did it look before upgrade in your end?

**Comment by SteffenLG** [comment]
Thanks for a very speedy reply! The schema before the upgrade looked like this:
![image](https://user-images.githubusercontent.com/67686676/231708148-49b4542c-90a2-4a83-ae69-43f56c27de59.png)
This is also what it looks like after the upgrade.

**Comment by LucGosso** [comment]
I see... please run on latest solita solution first runing the v2 update

https://github.com/huilaaja/RedirectManager/blob/c7ec6ea4b12aa36b53b27fa89bb373286fe0d53d/WebProject/Redirects/RedirectService.cs#L282

I will add this information for futur users.

**Comment by SteffenLG** [comment]
Thank you! I will let you know how it goes.

**Comment by SteffenLG** [comment]
Hi again. I've used the following commands to manually update the DB:
```
exec sp_rename 'SOLITA_Redirect', 'SEO_redirect';
ALTER TABLE [dbo].[SEO_redirect] ADD [Host][nvarchar](max) NULL;
```
This seemed simpler than updating the old code given my situation, and looks like it works. 

Thank you again for your assistance.
